name = "Marga"
main = "_worker.js"
compatibility_date = "2026-12-28"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "104.18.2.3"
UUID = "7f641943-2107-4b74-9779-2e6e0dc8394c"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
